### ISSUE TITLE
Remove Command & Make Route Unique

### ISSUE THREAD

**Issue by tielur** [hlcfan/alice_wiki#1]
I think we should remove the `command` but make the `route` more unique. Similar to how the [alice_google_images](https://hex.pm/packages/alice_google_images) works. Something like `wiki me` maybe.

**Comment by hlcfan** [comment]
You mean remove "route", keep "command", right?

If we remove "command", it will try to search every time a user says a word.

**Comment by tielur** [comment]
I would keep "route", just make the route something like `wiki me`. Similar to how the google images library uses `image me`. It's unique enough that you don't say it during normal conversation but a lot easier then using a command via `@alice wiki`. You could also keep both, as long as the route is more unique.

**Comment by tielur** [comment]
Right now any time you say "wiki" it's triggering it. Which you say during normal conversation. I would just change it to `wiki me` and leave the "command" if you want.

**Comment by hlcfan** [comment]
Makes sense. Keep it "route", see https://github.com/hlcfan/alice_wiki/blob/master/lib/alice/handlers/alice_wiki.ex#L12

**Comment by tielur** [comment]
👍 Let me know when you push a new release to hex.pm and I'll start using the handler!

**Comment by hlcfan** [comment]
It's up, http://hex.pm/packages/alice_wiki.

I'm gonna propose a PR for active alice later 😄
