### ISSUE TITLE
Multi word wikis

### ISSUE THREAD

**Issue by tielur** [hlcfan/alice_wiki#2]
Right now it's hard to search for wiki's that contain more then one word.

Examples:
`@alice wiki alice_in_wonderland`
> No Wikipedia entry found for 'aliceinwonderland'

`@alice wiki Lantern Festival`
> https://en.wikipedia.org/wiki/Lantern_Festival

`@alice wiki three blind mice`
> https://en.wikipedia.org/wiki/Three_Blind_Mice

`@alice wiki tater tots`
> https://en.wikipedia.org/wiki/Tater_tots

**Comment by hlcfan** [comment]
Case handled, https://github.com/hlcfan/alice_wiki/commit/21790e9b43165221a2dda56fdf6179a8ebdb8783 https://github.com/hlcfan/alice_wiki/commit/5341cf98f9792b3b9fd9ac4839581f867dace654

Thanks!
