### ISSUE TITLE
Handler Name Suggestion

### ISSUE THREAD

**Issue by tielur** [hlcfan/alice_wiki#3]
I'd suggest changing the [handler name](https://github.com/hlcfan/alice_wiki/blob/master/lib/alice/handlers/alice_wiki.ex#L3) to just `Alice.Handlers.Wiki` or `Alice.Handlers.WikiMe`. This would be a breaking change so maybe bump the major version?

This would follow a general pattern by the handlers already, for example:
```elixir
Alice.Handlers.GoogleImages 
Alice.Handlers.Shizzle
Alice.Handlers.Reddit
Alice.Handlers.Dogeme
Alice.Handlers.Eats
```

**Comment by hlcfan** [comment]
Makes sense, published to hex.pm, https://hex.pm/packages/alice_wiki.
Version marching to 1.x 😏
